// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzpdowhavqnanoxgkumg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cGRvd2hhdnFuYW5veGdrdW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjkxMzYsImV4cCI6MjA1ODM0NTEzNn0.bOT8pbxIxDQ9Lwz6YufvzBBuvyRPS2FvYU-cuHjR2nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);